### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by jwaltrip4** [Electronickss/TheaterTrailers#11]
For the life of me... I cannot get this to run in CRON

getting failed with Exit status 1

**Comment by jwaltrip4** [comment]
I have dug further....   I am getting:
---------------------------------------------------------------------------
  File "/opt/TheaterTrailers/TheaterTrailers.py", line 5, in <module>
    import youtube_dl
ImportError: No module named youtube_dl
----------------------------------------------------------

This runs just fine from the command line....  Just not from Cron in Ubuntu

**Comment by desepticon** [comment]
try calling the script explicitly with the path to your python binary.

**Comment by jwaltrip4** [comment]
None of that worked....
What finaly did today was i reinstalled youtube_dl and tmdbsimple using pip....

It was strange because if i ran from terminal it woild work just fine.  But would not run from cron
________________________________

**Comment by Electronickss** [comment]
I'm not sure how you had installed youtube_dl but yes installing through pip is a requirement
