### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by 2ndwonder** [Electronickss/TheaterTrailers#22]
Hi,

I'm trying to run TheaterTrailers on my Synology NAS but I can't seem to let it work.
getting the following error.

  File "/volume1/scripts/TheaterTrailers-master/theaterTrailers.py", line 189
    print e, 
            ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by TristBella** [comment]
you will get these errors if running python3 ...the file needs to be updated

**Comment by TristBella** [comment]
replace what is in your file with this
[theaterTrailers.txt](https://github.com/Electronickss/TheaterTrailers/files/6013437/theaterTrailers.txt)

**Comment by killmark-prog** [comment]
@TristBella I tried your file and now have the following errors

C:\Windows\system32>C:\Python\Python38\python.exe C:\Python\Python38\Scripts\The
aterTrailers\theaterTrailers.py
2021-03-16 14:46:32,177 - INFO - The cache is 0 days old
Traceback (most recent call last):
  File "C:\Python\Python38\Scripts\TheaterTrailers\theaterTrailers.py", line 464
, in <module>
    main()
  File "C:\Python\Python38\Scripts\TheaterTrailers\theaterTrailers.py", line 92,
 in main
    checkCashe()
  File "C:\Python\Python38\Scripts\TheaterTrailers\theaterTrailers.py", line 180
, in checkCashe
    checkVar = cacheDict[cacheDict.keys()[0]]['status']
TypeError: 'dict_keys' object is not subscriptable

Any thoughts?

**Comment by Darbunderscore** [comment]
> C:\Windows\system32>C:\Python\Python38\python.exe C:\Python\Python38\Scripts\The aterTrailers\theaterTrailers.py 2021-03-16 14:46:32,177 - INFO - The cache is 0 days old Traceback (most recent call last): File "C:\Python\Python38\Scripts\TheaterTrailers\theaterTrailers.py", line 464 , in main() File "C:\Python\Python38\Scripts\TheaterTrailers\theaterTrailers.py", line 92, in main checkCashe() File "C:\Python\Python38\Scripts\TheaterTrailers\theaterTrailers.py", line 180 , in checkCashe checkVar = cacheDict[cacheDict.keys()[0]]['status'] TypeError: 'dict_keys' object is not subscriptable
> 
> Any thoughts?

@killmark-prog Delete any .json cache files in the Cache directory.
