### ISSUE TITLE
Script syntax error

### ISSUE THREAD

**Issue by GlitchStorm** [Electronickss/TheaterTrailers#5]
When I run the script it throws a line 189, print e, taberror: inconsistent use of tabs and spaces in indentation

**Comment by ghost** [comment]
I was getting the same error. Running Python 3. I made this change to the code on line 189

```
except KeyError as e:
    logger.info('The cache is missing variables. Removing it.')
print (e )
os.remove(os.path.join(cacheDir, 'theaterTrailersCache.json'))
```
Put the print and the os.move so it's under the Except
